export const logAction = {
    REGISTER:'REGISTER',
    LOGIN:'LOGIN',
    SAVE_USER_INFO:'SAVE_USER_INFO',
    LOGOUT:'LOGOUT',
};

export const reportAction = {
    ADD_REPORT:'ADD_REPORT',
    USE_REPORT:'USE_REPORT',
    DROP_REPORT:'DROP_REPORT',
    TOP_REPORT:'TOP_REPORT',
    GET_REPORTS:'GET_REPORTS',
};

export const cardAction = {
    ADD_CARD:'ADD_CARD',
    DROP_CARD:'DROP_CARD',
    TOP_CARD:'TOP_CARD',
    COMPLETE_CARD:'COMPLETE_CARD',
    HANGUP_CARD:'HANGUP_CARD',
    GET_CARDS:'GET_CARDS',
};