export const appAction = {
    INITIAL_REPORTS:'INITIAL_REPORTS',
    RECEIVE_REPORT_SOCKET:'RECEIVE_REPORT_SOCKET',
    RECEIVE_MESSAGE:'RECEIVE_MESSAGE',
};

export const logAction = {
    REGISTER:'REGISTER',
    LOGIN:'LOGIN',
    SAVE_USER_INFO:'SAVE_USER_INFO',
    LOGOUT:'LOGOUT',
};

export const reportAction = {
    ADD_REPORT:'ADD_REPORT',
    GET_REPORTS:'GET_REPORTS',
};

export const cardAction = {
    ADD_CARD:'ADD_CARD',
    DROP_CARD:'DROP_CARD',
    TOP_CARD:'TOP_CARD',
    COMPLETE_CARD:'COMPLETE_CARD',
    HANGUP_CARD:'HANGUP_CARD',
    GET_CARDS:'GET_CARDS',
    ADD_DOCUMENT:'ADD_DOCUMENT',
    ADD_COMMENT:'ADD_COMMENT',
    ADD_MEMBERS:'ADD_MEMBERS',
    ADD_ACCESSORY:'ADD_ACCESSORY',
    ADD_ARTICLE:'ADD_ARTICLE',
    CURRENT_CARD:'CURRENT_CARD',
};

export const poolAction = {
    USE_REPORT:'USE_REPORT',
    DROP_REPORT:'DROP_REPORT',
    TOP_REPORT:'TOP_REPORT',
    CURRENT_REPORT:'CURRENT_REPORT',
};

export const UIAction = {
    SHOW_EDITOR_CREATE_MODAL:'SHOW_EDITOR_CREATE_MODAL',
    HIDDEN_EDITOR_CREATE_MODAL:'HIDDEN_EDITOR_CREATE_MODAL',
};